---
title: "223 Map Assignment 1"
author: "Shale Hunter and Caitlin Manley"
date: "9/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RColorBrewer)
library(rgeos)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(spData)
# library(spDataLarge)
library(here)
library(tidyverse)
library(tmap)
library(dplyr)
library(rgdal)
library(leaflet.providers)
library(leaflet)
library(ggplot2)
library(GGally)
library(basemaps)
library(ggmap)
```

## Loading data

```{r}
glacial_data = read_sf(here("data/ne_10m_glaciated_areas/ne_10m_glaciated_areas.shp"), promote_to_multi = TRUE)
```

## basic map

```{r}
tm_shape(glacial_data) + 
  tmap_options(check.and.fix = TRUE) +
  tm_polygons("recnum")
```

debugging via spData preloaded dataset
```{r}
tmap_mode("view")

tm_shape(cycle_hire) +
  tm_dots("nbikes") +
  tm_basemap(addProviderTiles("OpenStreetMap.BlackAndWhite"))
```

```{r}
tmap_mode("view")

tm_shape(cycle_hire_osm) +
  tm_dots("capacity") +
  leaflet() %>% 
  #addProviderTiles(providers$Thunderforest.SpinalMap)
  addTiles()
```

```{r}
ggplot(cycle_hire) +
  geom_sf() +
  # basemap_gglayer(ext, map_type = topographic)
  get_stamenmap()
```



```{r}

tmap_mode("plot")

tm_shape(land) +    
  tm_raster("elevation", palette = terrain.colors()) +
tm_shape(World) +
    tm_borders("white", lwd = .5) +
tm_shape(urban_agglomerations) +
  tm_dots("population_millions")
  
```


```{r}

tmap_mode("plot")

tm_shape(world) +
  tm_polygons() +
  tm_shape(urban_agglomerations) +
  tm_dots("population_millions")

```

```{r}

tmap_mode("view")

london <- leaflet() %>% setView(lng = 0.1275, lat = 51.5074, zoom = 10)

london %>% 
  addProviderTiles(providers$CartoDB.Positron) + 
  tm_shape(cycle_hire_osm) +
  tm_dots("capacity")
```

